# Setup compiler options and build folders
macro(SetupBuildSettings)
   ## BUILD FOLDERS ##

   # Create Cmake directories variables 
   if (NOT CMAKE_BINARY_OUTPUT_DIRECTORY)
      set(CMAKE_BINARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/bin)
      message(STATUS "Setting CMAKE_BINARY_OUTPUT_DIRECTORY to ${CMAKE_BINARY_OUTPUT_DIRECTORY}")
   endif()
   if (NOT CMAKE_LIBRARY_OUTPUT_DIRECTORY)
      set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib)
      message(STATUS "Setting CMAKE_LIBRARY_OUTPUT_DIRECTORY to ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
   endif()
   if (NOT CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
      set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/lib)
      message(STATUS "Setting CMAKE_ARCHIVE_OUTPUT_DIRECTORY to ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
   endif()

   ## COMPILER OPTIONS ##

   SET(CMAKE_CXX_STANDARD 23)
   SET(CMAKE_CXX_STANDARD_REQUIRED ON)
   SET(CMAKE_CXX_EXTENSIONS OFF)

endmacro()
